
server:
  #  port: 8001
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
#    min-response-size: 1024
#    level : 6

spring:
  mvc:
    cors :
      mapping: /api/**
      allowed-origins: http://localhost:3000
      allowed-methods: GET, POST, PUT, DELETE, PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  data:
    web:
      pageable:
        max-page-size: 30
        default-page-size: 20
        #        size-parameter: pageSize
        #        offset-parameter: page
        fallback-pageable:
          page-size: 20
#          sort: id,desc






